apiVersion: apps/v1 
# Deploys to Cluster
kind: Deployment
metadata:
  name: udacity-final-project
  labels:
    app: udacity-final-project
spec:
  selector:
    matchLabels:
      app: udacity-final-project
  replicas: 1
  template:
    metadata:
      labels:
        app: udacity-final-project
    spec:
      containers:
      - name: udacity-final-project
        image: jonastosti/udacity-final-project:latest
        ports:
        - name: http-server
        - containerPort: 8080

---
# Creates a service to allow access
apiVersion: v1
kind: Service
metadata:
  name: udacity-final-project-service
  labels:
    app: udacity-final-project-service
spec:
  type: LoadBalancer
  selector:
    app: udacity-final-project
  ports:
    - port: 8000
      targetPort: 8080
