apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-capstone
  strategy:
    rollingUpdate:
   #   maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
        - image: jonastosti/udacity-final-project:latest
          imagePullPolicy: Always
          name: udacity-capstone
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
