version: 2.1

jobs:
  ## CI JOBS
  build:
    docker:
      - image: cimg/openjdk:8.0.292
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: target/
          paths:
            - app.jar
  test:
    docker:
      - image: cimg/openjdk:8.0.292
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
  build-docker-image:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: target/
      - run:
          name: Build Docker Image
          command: docker build -t jonastosti/udacity-final-project:${CIRCLE_WORKFLOW_ID:0:7} . 
      - run:
          name: Push Docker Image
          command:  |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jonastosti/udacity-final-project:${CIRCLE_WORKFLOW_ID:0:7}              
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test
      - build-docker-image:
          requires:
          - build
          - test