version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  ## CI JOBS
  build:
    docker:
      - image: cimg/openjdk:8.0.292
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: target/
          paths:
            - app.jar
  test:
    docker:
      - image: cimg/openjdk:8.0.292
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
  lint:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=jonastosti_cloud-devops-nanodegree-final-project    
  build-docker-image:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: target/
      - run:
          name: Build Docker Image
          command: docker build -t jonastosti/udacity-final-project:${CIRCLE_WORKFLOW_ID:0:7} . 
      - run:
          name: Push Docker Image
          command:  |
            docker tag jonastosti/udacity-final-project:${CIRCLE_WORKFLOW_ID:0:7} jonastosti/udacity-final-project:latest
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jonastosti/udacity-final-project:latest 
  set-up-infrastructure:
     executor: aws-eks/python3
     steps:
       - checkout
       - run:
           name: Install the eksctl tool
           command: |
             if which eksctl > /dev/null; then
             echo "eksctl is already installed"
             exit 0
             fi
             mkdir -p eksctl_download
             curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/download/v0.73.0/eksctl_Linux_amd64.tar.gz" | tar xz -C eksctl_download
             chmod +x eksctl_download/eksctl
             SUDO=""
             if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
             SUDO="sudo"
             fi
             $SUDO mv eksctl_download/eksctl /usr/local/bin/
             rmdir eksctl_download 
       - run:
           name: Create Cluster
           command: |
            eksctl create cluster --name capstone-project --version 1.21 --nodegroup-name standard-workers --node-type t2.medium --nodes 3 --nodes-min 1 --nodes-max 4 --region us-west-1
  test-cluster:
    executor: aws-eks/python3
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstone-project
      - run:
          command: |
            kubectl get pods
            kubectl get svc
            kubectl get nodes
            kubectl get services
          name: Test cluster   
  deploy:
    executor: aws-eks/python3
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstone-project
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: false
          resource-file-path: deployment.yml
          resource-name: deployment/udacity-final-project
workflows:
  default: 
    jobs:
      - deploy
      - test-cluster:
          requires:
          - deploy 


 
